version: "3.9"
    
services:
    db:
        image: couchbase
        ports:
            - "8091-8094:8091-8094"
            - "11210:11210"
        restart: always
    
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "15672:15672"
            - "5672:5672"
        restart: always